[package]
name = "async-broadcast"
version = "0.4.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/smol-rs/async-broadcast"
documentation = "https://docs.rs/async-broadcast"
description = "Async broadcast channels"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Stjepan Glavina <stjepang@gmail.com>",
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
    "Zeeshan Ali <zeeshanak@gnome.org>",
]

[[bench]]
harness = false
name = "broadcast_bench"

[features]

[dependencies]
event-listener = "2.5.1"
futures-core = "0.3.14"
easy-parallel = "3.1.0"
parking_lot = "0.12.1"

[dev-dependencies]
criterion = "0.3"
doc-comment = "0.3.3"
futures-lite = "1.11.3"
futures-util = "0.3.14"
